export const tempUserData = {
  login: "Shurrd",
  id: 100307784,
  node_id: "U_kgDOBfqTSA",
  avatar_url: "https://avatars.githubusercontent.com/u/100307784?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Shurrd",
  html_url: "https://github.com/Shurrd",
  followers_url: "https://api.github.com/users/Shurrd/followers",
  following_url: "https://api.github.com/users/Shurrd/following{/other_user}",
  gists_url: "https://api.github.com/users/Shurrd/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Shurrd/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Shurrd/subscriptions",
  organizations_url: "https://api.github.com/users/Shurrd/orgs",
  repos_url: "https://api.github.com/users/Shurrd/repos",
  events_url: "https://api.github.com/users/Shurrd/events{/privacy}",
  received_events_url: "https://api.github.com/users/Shurrd/received_events",
  type: "User",
  site_admin: false,
  name: "Adeyemi Abraham",
  company: null,
  blog: "https://jesuisabraham.netlify.app/",
  location: "Nigeria",
  email: null,
  hireable: null,
  bio: "React Developer.\r\n",
  twitter_username: "shurrrrd",
  public_repos: 16,
  public_gists: 0,
  followers: 17,
  following: 17,
  created_at: "2022-02-23T17:37:02Z",
  updated_at: "2022-08-23T15:00:12Z",
};
